### ISSUE TITLE
[Bug] Error while running example app in appflowy-editor

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/appflowy-editor#158]
### Bug Description

When running the example app I am getting this error 

![Screenshot from 2023-06-01 19-32-51](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/77fdfca3-f848-4b4c-bf31-72c9d6cbbbcb)

I  am using - 
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/c1023bd9-5431-473c-bfb0-4af7a69c6a3e)

### How to Reproduce

Run the example app of flutter 

### Expected Behavior

Should run example app normally

### Operating System

Linux (Fedora Workstation 35)

### AppFlowy Editor Version(s)

1.0.0-dev.0

**Comment by alihassan143** [comment]
**their is issue with universal html plugin**
```
this will run your example app
universal_html:
    git:
       url: https://github.com/UsamaSarwar/universal_html
       ref: patch-1
```
