### ISSUE TITLE
[FR] remove the unused code and fix analysis issue.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/appflowy-editor#282]
### Description

The migration of editor have been done. So the excluded files should be removed.

```yaml
analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - lib/src/l10n/**
    # Remove the below directory until migration is complete.
    - test/**
    - lib/src/service/**
```

https://pub.dev/packages/appflowy_editor/score

### Impact

1. remove the unused code
2. increase the pub point
